Docker compose relies on environment variables for config

diff --git a/containers/horti-entrypoint b/containers/horti-entrypoint
--- a/containers/horti-entrypoint
+++ b/containers/horti-entrypoint
@@ -5,7 +5,9 @@ rm /root/.horticulturalist.lock 2> /dev/null
 
 echo Launching initial replication script
 cd /srv/software/offline_sync
-node src/initialReplication || { echo 'FATAL: Initial replication failure'; exit -1; }
+node js/initialReplication || { echo 'FATAL: Initial replication failure'; exit -1; }
+
+export COUCH_URL="${SATELLITE_COUCH_URL}/medic"
 
 echo Launching horticulturalist
 cd /srv/software/horticulturalist
